FROM ngaggion/chronoroot:latest

# Set working directory
WORKDIR /app/Segmentation

RUN git pull

# Set working directory
WORKDIR /app/Segmentation

RUN git pull

# Add a timestamp for last update 
RUN date > /app/Segmentation/ChronoRoot_nnUNet/last_update.txt

WORKDIR /app/