FROM ngaggion/chronorootbase:full

WORKDIR /

# MKDIR the /DATA directory for mounting data volumes
RUN mkdir /DATA

# Clone the ngaggion/chronoroot2 github repository into /app
RUN git clone https://github.com/ngaggion/ChronoRoot2.git /app